language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7
    - hhvm
    - hhvm-nigthly

matrix:
    allow_failures:
        - php: 7
        - php: hhvm
        - php: hhvm-nigthly

before_script:
    - composer install --no-interaction --prefer-source

    - cp ./tests/php.sample.ini ./tests/php.ini

script:
    - ./vendor/bin/tester -s ./tests/cases
