language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7
    - hhvm
    - hhvm-nigthly

matrix:
    allow_failures:
        - php: 7
        - php: hhvm-nightly

before_script:
    - composer install --no-interaction --prefer-source

    - cp ./tests/php.sample.ini ./tests/php.ini

    - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then cat ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini >> ./tests/php.ini; fi
    - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then NTESTER_FLAGS="--coverage ./coverage.xml --coverage-src ./src"; else TESTER_FLAGS=""; fi

script:
    - ./tests/run.sh -s $NTESTER_FLAGS ./tests/cases

after_script:
    - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then composer require satooshi/php-coveralls; fi
    - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then php vendor/bin/coveralls -c tests/.coveralls.yml -v; fi
